### PR TITLE
suppress rejected Tx log to Debug level

### LINKED ISSUE #2: Move log "rejected bad transaction" to debug level
## Summary
repost issue from https://github.com/tendermint/tendermint/issues/9981

the mempool V0 uses `DEBUG` but V1 uses `INFO` which might create a lot of noise in the log.

### PR DESCRIPTION
**Pull request by JayT106**
Closes #2

---

#### PR checklist

- [ ] Tests written/updated, or no tests needed
- [ ] `CHANGELOG_PENDING.md` updated, or no changelog entry needed
- [ ] Updated relevant documentation (`docs/`) and code comments, or no
      documentation updates needed

### CODE REVIEW

**Comment by adizere** [comment]
Thank you Jay for opening this PR. We'll help port this to the renamed fork of Tendermint Core as soon as we make that rename public (next week, we are working intensively on that). Thanks for your patience in the meantime!

**Comment by JayT106** [comment]
> Thank you Jay for opening this PR. We'll help port this to the renamed fork of Tendermint Core as soon as we make that rename public (next week, we are working intensively on that). Thanks for your patience in the meantime!

Sure!

**Comment by JayT106** [comment]
Close PR due to the mempool deprecation in the following release.

**Comment by sergio-mena** [comment]
@JayT106 migrated this PR to cometbft/cometbft. Closing

**Pull request closed without merging**
